spring.application.name=task-api

task-api.max-tasks=${TASK_API_MAX_TASKS:100}
spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:task_api}
spring.datasource.username=${DB_USERNAME:task_api_user}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

spring.flyway.schemas=public
