CREATE TABLE tasks
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY,
    title       VARCHAR(100) NOT NULL,
    description TEXT,
    status      VARCHAR(20)  NOT NULL DEFAULT 'TODO',
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at  TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_tasks PRIMARY KEY (id),

    CONSTRAINT chk_tasks_status CHECK (
        status IN ('TODO', 'IN_PROGRESS', 'DONE')
        ),

    CONSTRAINT chk_tasks_title_not_blank CHECK (
        LENGTH(TRIM(title)) > 0
        )
);