CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    email VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL,
    role VARCHAR(20) NOT NULL DEFAULT 'USER',
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_users PRIMARY KEY(id),
    CONSTRAINT uq_users_email UNIQUE(email),

    CONSTRAINT chk_users_role CHECK (
        role IN ('USER', 'ADMIN')
        ),

    CONSTRAINT chk_users_email_not_blank CHECK (
        LENGTH(TRIM(email)) > 0
        )
);
